name: rl
dependencies:
    - python==2.7.0
    - numpy==1.14.0
    - notebook==5.0.0
    - pip:
        - gym[atari]==0.9.2
        - gym==0.9.2
        - chainer==2.0.1
        - matplotlib==2.0.2
        - click==5.1.0
        - scipy==1.0.0
        - tensorflow==1.5.0
